name: 将GItee的最新release同步到Github

on:
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '将GItee的最新release同步到Github'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 您需要的 Python 版本

    - name: Install dependencies
      run: |
        pip install requests  # 安装所需的库

    - name: Run script
      run: |
        python ./script/sync-release-gitee2github.py  # 执行脚本