name: sync gitee regularly

on:
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '手动触发'

jobs:
  sync-gitee-regularly:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          rm -rf *

      - name: Checkout Github
        uses: actions/checkout@v3
        with:
          repository: dangehub/obsidian-i18n
          path: obsidian-i18n
          ref: main
          token: ${{ secrets.myGITHUB_ACCESS_TOKEN }}
        
      - name: Checkout Gitee repository
        run: |
          git clone https://song_of_light:${{ secrets.qudange_GITEE_ACCESS_TOKEN }}@gitee.com/zero--two/obsidian-i18n-translation.git

      - name: Copy files from Gitee to Github
        run: |
          cp -rf obsidian-i18n-translation/zh-cn/* obsidian-i18n/lang/zh-cn/

      - name: Commit and push
        run: |
          cd ./obsidian-i18n
          git config --global user.email "moruotaiqing@gmail.com"
          git config --global user.name "dangehub"
          git add -A
          git commit -m "Synced Gitee" || exit 0
          git push