name: Update vika regularly

on:
#  schedule:
#    - cron: '0 */1 * * *'  # 每小时运行一次
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '手动触发'

jobs:
  Update-vika-regularly:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          rm -rf *
          
      - name: Checkout Gitee repository
        run: |
          git clone https://song_of_light:${{ secrets.qudange_GITEE_ACCESS_TOKEN }}@gitee.com/zero--two/obsidian-i18n-translation.git
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm
      
      - name: Run update script
        env:
          VIKA_API_KEY: ${{ secrets.VIKA_API_KEY }}
        run: |
          cd obsidian-i18n-translation
          python script/update_vika.py